### PR TITLE
Upgrade to Storybook 8

### PR DESCRIPTION
**Pull request by ShaunEvening**
## What changed

- [x] Update to node 18
- [x] Update Storybook to v8
- [x] Update React to v18
- [x] Add `@storybook/addon-webpack5-compiler-swc` for compiler
- [x] Remove mdx-gfm addon
- [x] Replace use of `@storybook/addons` with `@storybook/manager-api` and `@storybook/preview-api`

# Version

Published prerelease version: `v8.0.0-next.1`

<details>
  <summary>Changelog</summary>

  #### ⚠️ Pushed to `next`
  
  - broaden version ranges ([@ndelangen](https://github.com/ndelangen))
  - Set version to 8 alpha ([@ShaunEvening](https://github.com/ShaunEvening))
  - Temporarily remove broken addon ([@ShaunEvening](https://github.com/ShaunEvening))
  - Update some stories to CSF3 ([@ShaunEvening](https://github.com/ShaunEvening))
  - Remove old mdx addon ([@ShaunEvening](https://github.com/ShaunEvening))
  - Add missing typings ([@ShaunEvening](https://github.com/ShaunEvening))
  - Update to React18; Update to SB8 ([@ShaunEvening](https://github.com/ShaunEvening))
  - Update node version ([@ShaunEvening](https://github.com/ShaunEvening))
  
  #### Authors: 2
  
  - Norbert de Langen ([@ndelangen](https://github.com/ndelangen))
  - Shaun Evening ([@ShaunEvening](https://github.com/ShaunEvening))
</details>

### CODE REVIEW

**Comment by ndelangen** [comment]
@SocketSecurity ignore @sinclair/typebox@0.27.8
@SocketSecurity ignore @storybook/addon-actions@8.0.0-alpha.10
@SocketSecurity ignore @storybook/addon-links@8.0.0-alpha.10
@SocketSecurity ignore @storybook/manager@8.0.0-alpha.10
@SocketSecurity ignore @storybook/preview@8.0.0-alpha.10
@SocketSecurity ignore assert@2.1.0
@SocketSecurity ignore react@18.2.0
@SocketSecurity ignore react-dom@18.2.0
@SocketSecurity ignore scheduler@0.23.0
@SocketSecurity ignore hasown@2.0.0
@SocketSecurity ignore handlebars@4.7.8
@SocketSecurity ignore get-stream@8.0.1
@SocketSecurity ignore foreground-child@3.1.1

**Comment by ndelangen** [comment]
@SocketSecurity ignore npm/react@18.2.0
@SocketSecurity ignore npm/react-dom@18.2.0
@SocketSecurity ignore npm/scheduler@0.23.0
@SocketSecurity ignore npm/foreground-child@3.1.1
@SocketSecurity ignore npm/handlebars@4.7.8
@SocketSecurity ignore npm/assert@2.1.0
@SocketSecurity ignore npm/get-stream@8.0.1

**Comment by ndelangen** [comment]
@yannbf I think these version ranges should make it future compatible.. WDYT?

**Review by yannbf — CHANGES_REQUESTED** [review]
Reminder NOT to merge this PR until Storybook 8 reaches stable. In the time being, as we push to this branch, a new `next` version will be generated.

**Pull request merged**
