### PR TITLE
Archive changelog and link addon changelog to root

### LINKED ISSUE #220: Changelog & Git version tags
### Affected design types

- [ ] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

Currently releases are only published on npmjs.com and the changelog is not kept up to date.

This makes it difficult to identify new functionality and changes without resorting to diffing the git history which is less than optimal. It's also hard to identify which commits are used in the releases since they aren't tagged in git, and no github releases are provided.

I apologies if this would be better of as a discussion, I view it as a bug in the release process hence an issue, but I can also appreciate that it's not technically a defect in the code.

### How to reproduce the bug?

Notice an update on npm, attempt to identify what has changed.

### Expected behaviour

Up to date changelog and tagged git releases.

### Environment

- [ ] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

7.0.7

### Storybook versions

7.3.0

### PR DESCRIPTION
**Pull request by shilman**
Closes #220

@pocka I tried to configure [Auto](https://intuit.github.io/auto/) to output `CHANGELOG.md` to the root, but didn't see an option for that. For now I've created a symbolic link from the package changelog to the root directory. If you have better ideas I'm open to trying other things. WDYT?

### CODE REVIEW

**Comment by pocka** [comment]
> @pocka I tried to configure [Auto](https://intuit.github.io/auto/) to output `CHANGELOG.md` to the root, but didn't see an option for that. For now I've created a symbolic link from the package changelog to the root directory. If you have better ideas I'm open to trying other things. WDYT?

Unfortunately GitHub (still) does not support symlink on their web UI...
https://github.com/storybookjs/addon-designs/blob/shilman/fix-changelog/CHANGELOG.md

Maybe having a `<repo root>/CHANGELOG.md` that have something like below would be good enough (better than nothing).

```md
See <./packages/storybook-addon-designs/CHANGELOG.md>
```

**Comment by shilman** [comment]
@pocka fair point. updated!

**Comment by pocka** [comment]
Thanks, looks good to me!

**Comment by shilman** [comment]
Thanks so much for pointing it out!

**Pull request merged**
